//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhSpace {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BLogs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BLogs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WhSpace.BLogs", typeof(BLogs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Site administrator) Changed corporation main administrator to.
        /// </summary>
        internal static string corporationAdminChange {
            get {
                return ResourceManager.GetString("corporationAdminChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . Old administrator was.
        /// </summary>
        internal static string corporationAdminChange1 {
            get {
                return ResourceManager.GetString("corporationAdminChange1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed logs language. Old language was.
        /// </summary>
        internal static string corporationChangeLogsLang {
            get {
                return ResourceManager.GetString("corporationChangeLogsLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed corporation name. Old name was.
        /// </summary>
        internal static string corporationChangeName {
            get {
                return ResourceManager.GetString("corporationChangeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered the corporation.
        /// </summary>
        internal static string corporationRegister {
            get {
                return ResourceManager.GetString("corporationRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and himself..
        /// </summary>
        internal static string corporationRegister2 {
            get {
                return ResourceManager.GetString("corporationRegister2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added new member with username.
        /// </summary>
        internal static string memberAddNew {
            get {
                return ResourceManager.GetString("memberAddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted member.
        /// </summary>
        internal static string memberDelete {
            get {
                return ResourceManager.GetString("memberDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed type of member.
        /// </summary>
        internal static string memberEditType {
            get {
                return ResourceManager.GetString("memberEditType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added operation ID:.
        /// </summary>
        internal static string operationAdd {
            get {
                return ResourceManager.GetString("operationAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted operation ID:.
        /// </summary>
        internal static string operationDelete {
            get {
                return ResourceManager.GetString("operationDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , added on.
        /// </summary>
        internal static string operationGeneralWhichWasAdded {
            get {
                return ResourceManager.GetString("operationGeneralWhichWasAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated info for operation ID:.
        /// </summary>
        internal static string operationInfoUpdated {
            get {
                return ResourceManager.GetString("operationInfoUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed length of operation ID:.
        /// </summary>
        internal static string operationLenghtChange {
            get {
                return ResourceManager.GetString("operationLenghtChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added.
        /// </summary>
        internal static string operationLootAdd {
            get {
                return ResourceManager.GetString("operationLootAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to opertaion ID:.
        /// </summary>
        internal static string operationLootAdd2 {
            get {
                return ResourceManager.GetString("operationLootAdd2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed.
        /// </summary>
        internal static string operationLootDelete {
            get {
                return ResourceManager.GetString("operationLootDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from operation ID:.
        /// </summary>
        internal static string operationLootDelete2 {
            get {
                return ResourceManager.GetString("operationLootDelete2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed information for loot.
        /// </summary>
        internal static string operationLootEdit {
            get {
                return ResourceManager.GetString("operationLootEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in operation ID:.
        /// </summary>
        internal static string operationLootEdit2 {
            get {
                return ResourceManager.GetString("operationLootEdit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed the system in wich was operation ID:.
        /// </summary>
        internal static string operationSystemChange {
            get {
                return ResourceManager.GetString("operationSystemChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed tax of operation ID:.
        /// </summary>
        internal static string operationUpdateTax {
            get {
                return ResourceManager.GetString("operationUpdateTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated tax info for operation ID:.
        /// </summary>
        internal static string operationUpdateTaxInfo {
            get {
                return ResourceManager.GetString("operationUpdateTaxInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added.
        /// </summary>
        internal static string operationUserAdd {
            get {
                return ResourceManager.GetString("operationUserAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to operation ID:.
        /// </summary>
        internal static string operationUserAdd2 {
            get {
                return ResourceManager.GetString("operationUserAdd2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed.
        /// </summary>
        internal static string operationUserDelete {
            get {
                return ResourceManager.GetString("operationUserDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from operation ID:.
        /// </summary>
        internal static string operationUserDelete2 {
            get {
                return ResourceManager.GetString("operationUserDelete2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed participating information for.
        /// </summary>
        internal static string operationUserEdit {
            get {
                return ResourceManager.GetString("operationUserEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in operation ID:.
        /// </summary>
        internal static string operationUserEdit2 {
            get {
                return ResourceManager.GetString("operationUserEdit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added signature.
        /// </summary>
        internal static string signatureAdd {
            get {
                return ResourceManager.GetString("signatureAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        internal static string signatureAdd2 {
            get {
                return ResourceManager.GetString("signatureAdd2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted signature.
        /// </summary>
        internal static string signatureDelete {
            get {
                return ResourceManager.GetString("signatureDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        internal static string signatureDelete2 {
            get {
                return ResourceManager.GetString("signatureDelete2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated signature.
        /// </summary>
        internal static string signatureEdit {
            get {
                return ResourceManager.GetString("signatureEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        internal static string signatureEdit2 {
            get {
                return ResourceManager.GetString("signatureEdit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added system.
        /// </summary>
        internal static string systemAdd {
            get {
                return ResourceManager.GetString("systemAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to connected with.
        /// </summary>
        internal static string systemAdd2 {
            get {
                return ResourceManager.GetString("systemAdd2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed class of system.
        /// </summary>
        internal static string systemClassChange {
            get {
                return ResourceManager.GetString("systemClassChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted system.
        /// </summary>
        internal static string systemDelete {
            get {
                return ResourceManager.GetString("systemDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed effect of system.
        /// </summary>
        internal static string systemEffectChange {
            get {
                return ResourceManager.GetString("systemEffectChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated info for system.
        /// </summary>
        internal static string systemInfoUpdate {
            get {
                return ResourceManager.GetString("systemInfoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed system.
        /// </summary>
        internal static string systemNameChange {
            get {
                return ResourceManager.GetString("systemNameChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name to.
        /// </summary>
        internal static string systemNameChange2 {
            get {
                return ResourceManager.GetString("systemNameChange2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated occupation info for system.
        /// </summary>
        internal static string systemOccupationUpdate {
            get {
                return ResourceManager.GetString("systemOccupationUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted wormholes, which lead from.
        /// </summary>
        internal static string wormDelete {
            get {
                return ResourceManager.GetString("wormDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        internal static string wormDelete2 {
            get {
                return ResourceManager.GetString("wormDelete2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and backwards..
        /// </summary>
        internal static string wormDelete3 {
            get {
                return ResourceManager.GetString("wormDelete3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed wormhole ID, which leads from.
        /// </summary>
        internal static string wormEdit {
            get {
                return ResourceManager.GetString("wormEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        internal static string wormEdit2 {
            get {
                return ResourceManager.GetString("wormEdit2", resourceCulture);
            }
        }
    }
}
