//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Business {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Business() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Business", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plexes.
        /// </summary>
        internal static string operationBasedOnPlexes {
            get {
                return ResourceManager.GetString("operationBasedOnPlexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to time.
        /// </summary>
        internal static string operationBasedOnTime {
            get {
                return ResourceManager.GetString("operationBasedOnTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to isk.
        /// </summary>
        internal static string operationIskCutTypeIsk {
            get {
                return ResourceManager.GetString("operationIskCutTypeIsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plexes count.
        /// </summary>
        internal static string operationPlexesCountLong {
            get {
                return ResourceManager.GetString("operationPlexesCountLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to count.
        /// </summary>
        internal static string operationPlexesLength {
            get {
                return ResourceManager.GetString("operationPlexesLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to length.
        /// </summary>
        internal static string operationTimeLength {
            get {
                return ResourceManager.GetString("operationTimeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        internal static string operationTimeLengthLong {
            get {
                return ResourceManager.GetString("operationTimeLengthLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to combat.
        /// </summary>
        internal static string operationTypeCombat {
            get {
                return ResourceManager.GetString("operationTypeCombat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gas harvesting.
        /// </summary>
        internal static string operationTypeGasHarvesting {
            get {
                return ResourceManager.GetString("operationTypeGasHarvesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page:.
        /// </summary>
        internal static string page {
            get {
                return ResourceManager.GetString("page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not scanned.
        /// </summary>
        internal static string signatureNotScanned {
            get {
                return ResourceManager.GetString("signatureNotScanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wormhole.
        /// </summary>
        internal static string signatureWormhole {
            get {
                return ResourceManager.GetString("signatureWormhole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wormhole.
        /// </summary>
        internal static string sysClassWormhole {
            get {
                return ResourceManager.GetString("sysClassWormhole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no effect.
        /// </summary>
        internal static string sysEffectNoEffect {
            get {
                return ResourceManager.GetString("sysEffectNoEffect", resourceCulture);
            }
        }
    }
}
